version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py  # Si vous utilisez Sphinx


python:
  install:
    - requirements: docs/requirements.txt  # Ou le chemin d'un fichier contenant les dépendances
